# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  postgre:
    container_name: postgre
    image: postgres:13.3
    restart: always
    # volumes:
    #   - ~/volumes/jhipster/todoDemo/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=todoDemo
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
